/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.User;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import util.DatabaseConnector;

/**
 *
 * @author thamashikumarasinghe
 */
public class Form extends javax.swing.JPanel {

    /**
     * Creates new form Form
     */
    private JPanel viewPanel;

    public Form(JPanel bottomPanel) {
        initComponents();
        this.viewPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        firstnameTxtField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        firstnameValidation = new javax.swing.JLabel();
        ageValidation = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        headingLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        headingLabel.setText("Registration Form");

        firstnameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        firstnameLabel.setText("Full name");

        firstnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameTxtFieldFocusLost(evt);
            }
        });
        firstnameTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstnameTxtFieldMouseExited(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ageLabel.setText("Age");

        ageTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageTextFieldFocusLost(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(51, 153, 255));
        submitBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        firstnameValidation.setForeground(new java.awt.Color(255, 0, 0));

        ageValidation.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(firstnameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(124, 124, 124)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ageValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headingLabel)
                            .addComponent(firstnameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headingLabel)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstnameLabel)
                            .addComponent(firstnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstnameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ageLabel))
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ageValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(335, 335, 335)
                .addComponent(submitBtn)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameTxtFieldFocusGained
        // TODO add your handling code here:
        firstnameValidation.setText("");
    }//GEN-LAST:event_firstnameTxtFieldFocusGained

    private void firstnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameTxtFieldFocusLost
        // TODO add your handling code here:
        if (firstnameTxtField.getText() == null || firstnameTxtField.getText().isEmpty()) {
            firstnameValidation.setText("First name is empty");
        }
    }//GEN-LAST:event_firstnameTxtFieldFocusLost

    private void firstnameTxtFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnameTxtFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtFieldMouseExited

    private void ageTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTextFieldFocusGained
        // TODO add your handling code here:
        ageValidation.setText("");
    }//GEN-LAST:event_ageTextFieldFocusGained

    private void ageTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTextFieldFocusLost
        // TODO add your handling code here:
        try {
            if (ageTextField.getText() == null || ageTextField.getText().isEmpty()) {
                ageValidation.setText("Age is empty");
            } else if (ageTextField.getText().length() > 3) {
                ageValidation.setText("Age is invalid. Please enter a valid age!");
            } else {
                for (int i = 0; i < ageTextField.getText().length(); i++) {
                    if (Character.isDigit(ageTextField.getText().charAt(i)) == false) {
                        ageValidation.setText("Age contains invalid characters. Please enter a valid age!");
                    }
                }

            }

        } catch (NumberFormatException e) {

        }
    }//GEN-LAST:event_ageTextFieldFocusLost

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        //        String firstname, lastname, age, email, message;
        User user = new User();
        try {

            // validation for submit button
            if (firstnameTxtField.getText() == null || firstnameTxtField.getText().isEmpty()) {
                firstnameValidation.setText("First name is empty");
            }
            // validation for submit button
            if (ageTextField.getText() == null || ageTextField.getText().isEmpty()) {
                ageValidation.setText("Age is empty");
            }

            user.setName(firstnameTxtField.getText());
            user.setAge(Integer.parseInt(ageTextField.getText()));
            DatabaseConnector.addUser(user);
            JOptionPane.showMessageDialog(null, "User Registered Successfully", "Succesful Registration", JOptionPane.INFORMATION_MESSAGE);
            cleanup();
        } catch (Exception e) {
            System.out.println("Error" + e);
            JOptionPane.showMessageDialog(this, "Error while Registering!" + e.getMessage());

        }
    }//GEN-LAST:event_submitBtnActionPerformed
    public void cleanup() {
        firstnameTxtField.setText("");
        ageTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel ageValidation;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTxtField;
    private javax.swing.JLabel firstnameValidation;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
